### ISSUE TITLE
giving up.. too damn complicated just to retrieve some already public data

### ISSUE THREAD

**Issue by perseon** [aweber/public-api-examples#48]
I've spent a few hours to no avail. Can't seem to get a token. I always get "Invalid redirect URI"
created an app with http://localhost:3000/callback as callback url (got client_id, client_secret)
read all the docs everywere
changed everything .. same idiotic error (couldn't maybe just say what the * is wrong with my URI?)
and the thing is.. i just wanted to get something that was public anyway. why this convoluted scheme just to get some data? why not a clean, expressive api just like github has?
sorry for the rant but it's a long time since I've bumped into a clueless error like this one.

**Comment by dave-shawley** [comment]
@perseon -- I am sorry that this is so finicky.  The `redirect_uri` parameter has to be an **exact match** of one that you have entered in your AWeber Labs application (e.g., https://labs.aweber.com/apps).  Make sure that you are using the exact URL that you have specified there including trailing slashes, port number, query parameters, etc.  I've created a ticket to address this in the troubleshooting section of our documentation since we don't mention this explicitly.

This is a common requirement in OAuth 2 applications since the specification requires the exact match.  We definitely need to do a better job of calling out the exact problem.  Feel free to reach out to us at api@aweber.com when you run into issues.

**Comment by perseon** [comment]
Yes, as you said this was standard, and I was tired and probably missed something over and over. There was nothing wrong with the demo code or the API, or the documentation which is exhaustive and well written, I just kept making the same mistake. It's almost embarrassing.

Thank you and sorry.

**Comment by dave-shawley** [comment]
@perseon thanks creating the issue.  It spurred a nice discussion inside of our team and improved our product so I very much welcome the feedback.  We ended up rewording some of our error messaging so you would now receive an error page like this:

![image](https://user-images.githubusercontent.com/350812/82449365-1d35b200-9a79-11ea-9281-b280fde8311d.png)

**Comment by perseon** [comment]
Well, 

I'm glad something god came out of my misery.
